### PR TITLE
chore(dockerfile): optimize workspace build performance

### PR DESCRIPTION
**Pull request by fuxingloh**
#### What this PR does / why we need it:

To speed up GitHub actions cycle time and concurrency since GH actions only allow 20 workflows to be run at any time.

### CODE REVIEW

**Comment by fuxingloh** [comment]
I checked `legacy-api`, and it works as expected.

Should we deploy this?

**Comment by kodemon** [comment]
> I checked `legacy-api`, and it works as expected.
> 
> Should we deploy this?

If it works as expected and improves performance I say 🚀

**Review by kodemon — APPROVED** [review]

**Review by surangap — APPROVED** [review]

**Comment by nichellekoh** [comment]
I pulled the image and ran for `status-api`. It is working as expected 👍🏼

**Review by nichellekoh — APPROVED** [review]

**Comment by fuxingloh** [comment]
Looks good, I checked the dist too, it compiled properly as expected.

**Pull request merged**
