### PR TITLE
chore(whale/sanity-testing): port over tests from whale ci newman

### PR DESCRIPTION
**Pull request by eli-lim**
#### What this PR does / why we need it:
Ports over the sanity tests from https://github.com/JellyfishSDK/whale/blob/main/.github/workflows/ci/postman_collection.json as typescript + jest tests

#### Which issue(s) does this PR fixes?:
Part of #977 

#### Additional comments?:
- One thing to note is that the CI pipeline now builds whale twice. We can investigate in a future PR the possibility of sharing the build (output of the `build` workflow) with the sanity test env.

### CODE REVIEW

**Comment by jingyi2811** [comment]
Every time I rerun the test, the system will build the image again. I wonder if the following code can change from `docker.buildimage` to `docker.getimage`
See https://github.com/JellyfishSDK/jellyfish/blob/main/jest.sanity.setup.js#L26

Refer to https://github.com/JellyfishSDK/jellyfish/blob/main/packages/testcontainers/src/containers/DockerContainer.ts#L141

**Comment by eli-lim** [comment]
> Every time I rerun the test, the system will build the image again. I wonder if the following code can change from `docker.buildimage` to `docker.getimage`
> 
> if the image was built BEFORE

If the underlying (whale) code changes, will docker be aware and rebuild the image?

**Review by canonbrother — APPROVED** [review]

**Comment by jingyi2811** [comment]
> > Every time I rerun the test, the system will build the image again. I wonder if the following code can change from `docker.buildimage` to `docker.getimage`
> > if the image was built BEFORE
> 
> @jingyi2811 thanks for the suggestion. But if the underlying (whale) code changes, will docker be aware and rebuild the image?

If there are code changes, a new docker name needs to be given and rebuild is needed.

**Comment by jingyi2811** [comment]
If it is too hard then just ignore it, I am using an old Mac book with an Intell processor. Running tests on every test unit takes me 5 to 10 minutes.

**Comment by kodemon** [comment]
There is definitely room for optimization improvements to the sanity layer dedicating more time to the process. The current main use case for our whale sanity tests is mostly in our devops/releases processes. It's separated from the standard unit tests, as its a pretty heavy handed process so we decided to make it opt in. _(No one wants to wait 5 - 10 minutes when running local unit tests)_ 😅

**Review by kodemon — APPROVED** [review]

**Review by jingyi2811 — APPROVED** [review]

**Review by ivan-zynesis — APPROVED** [review]

**Pull request merged**
